package com.amg.dinningphilosophers.response;

public
enum ResponseType {

    REGISTERED,ALIVE_CONNECTION, STARTED, GIVE_RIGHT_CHOPSTICK, GIVE_LEFT_CHOPSTICK, EAT,RIGHT_CHOPSTICK_IN_USE,LEFT_CHOPSTICK_IN_USE,WAIT,ERROR_NO_SERVER,FIRST_RIGHT_CHOPSTICK,FIRST_LEFT_CHOPSTICK,LEFT_PHILOSOPHER_JUSTICE,RIGHT_PHILOSOPHER_JUSTICE


}
